### PR TITLE
8 as user i would like to see standard unhcr color and font in order to recognise the brand

### LINKED ISSUE #8: As user, I would like to see standard UNHCR color and font in order to recognise the brand
## Client - Validation 

+ [ ] Check that we have the right color

## Dev - Tech

+ [ ] Add a theming function

### PR DESCRIPTION
**Pull request by Edouard-Legoupil**
- Does my code meet the quality standards for releasing packages?
- Does the reviewer have all the information to validate the features/issues without too much research?
- Does the customer who will validate the associated tickets have the information to do so without wasting time?

## Issues to validate to close : 

- [ ] [issue #](https://github.com/UNHCR-Guatemala/A2SIT/issues/8)

 

## Checklist:

- [ ] Does the package check go local?
- [ ] Does the CI pass?
- [ ] Are the added / fixed features documented, tested?
- [ ] Are the added features / solved problems briefly presented in the PM message?
- [ ] Are the changes related to tickets / issues that I have listed in the commits and in the PM itself?
- [ ] Are the tickets in "review" mode in the Project Tracking Board?
- [ ] Does each ticket, if it is to be closed after acceptance of the PR, contain a comment that tells how to validate it?

### CODE REVIEW

**Comment by bluefoxr** [comment]
Hi @Edouard-Legoupil thanks for working on themeing the app! I addressed the CMD errors to do with not declaring some packages (I normally use `usethis::use_package()` for this).

I am just wondering though if we can adjust the colours somehow as eg. the contrast between the boxes and the background is quite low, and some of the colours are a bit bright. Also can we use a different font - it looks like you were aiming for Lato but the result (at least on my PC) is Times New Roman. Do I need to install a font locally perhaps?

**Comment by Edouard-Legoupil** [comment]
Indeed - I agree and we can probably improve that ShinyApp theming..  

Also the function used now https://github.com/UNHCR-Guatemala/A2SIT/blob/8-as-user-i-would-like-to-see-standard-unhcr-color-and-font-in-order-to-recognise-the-brand/R/theme.R  comes from https://github.com/nik01010/dashboardthemes/blob/master/R/CreateTheme_shinyDashboardThemeDIY.R  and is just a way to create a css

The package itself  https://github.com/nik01010/dashboardthemes might be removed from CRAN -

We need to work with our designer [@vidonne](https://github.com/vidonne/)  to get some UNHCR branded css for shinyDashboard - Will follow up with him on this!

**Comment by Edouard-Legoupil** [comment]
I suggest we merge this for now - will add the css later on!

**Comment by bluefoxr** [comment]
Ok fair enough!

**Pull request merged**
