### PR TITLE
Small UI changes

### PR DESCRIPTION
**Pull request by bluefoxr**
Small merge for some previous changes

### CODE REVIEW

**Comment by bluefoxr** [comment]
Hi @Edouard-Legoupil this branch is some small changes that I would like to merge in. Let me know if you have any comments before the merge.

Note that at the moment I am not including unit testing in the interests of getting early feedback on the app design and functionality. Later in the development I will ensure the functions are also tested properly where appropriate. Roughly speaking, I would like to get an prototype running, which can then be adjusted and refined afterwards.

**Comment by bluefoxr** [comment]
p.s. the CMD check fails look to be not due to the package - sometimes they fail due to connectivity issues I think, but it looks as if the package is passing otherwise.

**Review by Edouard-Legoupil — APPROVED** [review]
Hi Will - good for me! and totally agree with the idea of getting asap a prototype overview!

**Comment by bluefoxr** [comment]
Ok thanks, merging now...

**Pull request merged**
